version: "2.15.1"
services: 
  api: 
    build: ./api
    container_name: api_server_c1
    ports: 
      - '4000:4000'
    volumes:
      - ./api:/app
      - /app/node_modules
  react-app: 
    build: ./vite-react-project
    container_name: react_app_c
    ports: 
      - '5173:5173'
    stdin_open: true
    tty: true


# to run
# docker-compose up